// Below are the values for each room.  Edit the values to alter the site.
var roomValues = [
  {
    number: 1,
    name: "The Halibut Room",
    king: 2,
    queen: 0,
    twin: 0,
    whether: "yes",
    occupants: 6,
    price: 319,
  },
  {
    number: 2,
    name: "Steelhead Salmon Room",
    king: 1,
    queen: 0,
    twin: 0,
    whether: "yes",
    occupants: 2,
    price: 209,
  },
  {
    number: 3,
    name: "Sockeye Salmon Room",
    king: 1,
    queen: 0,
    twin: 0,
    whether: "yes",
    occupants: 2,
    price: 209,
  },
  {
    number: 4,
    name: "Silver Salmon Room",
    king: 2,
    queen: 0,
    twin: 0,
    whether: "no",
    occupants: 4,
    price: 229,
  },
  {
    number: 5,
    name: "King Salmon Room",
    king: 1,
    queen: 0,
    twin: 1,
    whether: "no",
    occupants: 3,
    price: 229,
  },
  {
    number: 6,
    name: "Pink Salmon Room",
    king: 0,
    queen: 1,
    twin: 1,
    whether: "no",
    occupants: 3,
    price: 169,
  },
];
